### ISSUE TITLE
Table doesnt update on changing to template variable whose query returns no result

### ISSUE THREAD

**Issue by vaibhavinbayarea** [briangann/grafana-datatable-panel#1]
Hi,

I'm trying to use this panel as it has a lot more features than standard table. I'm running into an issue where if a template variable is present, and its changed from its initial value to a variable which does not have any values (in specified time period), the table does not update and continues to show the old data.

Steps to reproduce:
1. Select a template variable which will return data values in the specified time period
2. Add a datatable panel
3. Select Elasticsearch datasource
4. Create query with option: "name:$Template_name", raw_document
5. Additional options: (scrolling, search enabled)
5. Exit from Edit screen
6. The table should populate
7. Select a template variable value which does not have any entries in the specified time period.
8. The table will continue to show the old data rather than cleaning up entries.

Let me know if more information is required!

Thanks.

**Comment by briangann** [comment]
I'll try this out and fix asap - if you have fix a PR would be great :)

**Comment by PaulKuiper** [comment]
I had the same priblem :-)

**Comment by jonyrock** [comment]
Hey, I fixed this in my fork https://github.com/jonyrock/grafana-datatable-panel/

![screen shot 2017-06-12 at 20 23 29](https://user-images.githubusercontent.com/1022757/27046422-05cb9ec8-4fad-11e7-9894-c766c6584629.png)

Issue copy https://github.com/jonyrock/grafana-datatable-panel/issues/5

**Comment by briangann** [comment]
excellent, can you create a pull request and i'll get it merged in?

**Comment by briangann** [comment]
I'll try to merge in your changes, that's quite a bit of work you did there :)

**Comment by jonyrock** [comment]
@briangann this is what I am talking about. This is the problem. Maybe we can make a new version together ?

**Comment by briangann** [comment]
let's see if it will do a clean merge and test the result

**Comment by briangann** [comment]
clean merge isn't possible - we'll have to cherry pick the changes to unify the code.  I looked over the changes, lots of great work in there :)

**Comment by briangann** [comment]
the no-data fix has been implemented based on jonyrock's fork, it's in v0.0.3 now
