### ISSUE TITLE
FEAT: Add Individual column searching (text inputs)

### ISSUE THREAD

**Issue by robertknorton** [briangann/grafana-datatable-panel#102]
This Grafana Datatable plugin is amazing and for my Grafana purposes does nearly exactly what I need. The added search feature is great but I wish to be able to have the option to search each column individually. Since this plugin is based on datatables.net work I figured I'd start looking through their documentation. I found an example on how to add text searching for individual columns. I have copied the link below.
I would do a pull myself but I am very unfamiliar with Grafana and how to make plugins. If there is anything I could do to help get this feature added to your awesome plugin please let me know.

https://www.datatables.net/examples/api/multi_filter.html

It looks like many other contributors also left comments on how to put the search boxes at the top of the datatable, only search on keypress Enter, as well as an OR operand within the search text box to allow multi-value searches at once.

**Comment by iruizr7** [comment]
I implemented this in my PR https://github.com/briangann/grafana-datatable-panel/pull/101

**Comment by robertknorton** [comment]
This issue can be closed. Iruizr7 has implemented a solution.
