### ISSUE TITLE
Sorting not working Grafana 7

### ISSUE THREAD

**Issue by pbuxtonccuk** [briangann/grafana-datatable-panel#104]
There seems to be lots of issues with sorting of columns now.... it doesn't work in the slightest for most content.   The up/down arrows change, but the content of the grid doesn't to reflect the change.  Seems ok with numeric fields only

**Comment by richprice36** [comment]
Have the same issue, any resolution on the way?

**Comment by rntbrgtt** [comment]
Same issue for me.
Using Grafana 7.0.1 and Data Table Pabel 1.0.1.
sort works with integers but not string.

**Comment by McAnix** [comment]
Same issue my side
Grafana 7.0.3 and Data table 1.0.1.
