### ISSUE TITLE
Table Display - Font Size not working - Grafana 7

### ISSUE THREAD

**Issue by rntbrgtt** [briangann/grafana-datatable-panel#105]
Hi,

"Table Display - Font size" is not working for me. Using 80% or 250% is the same.

grafana v7.0.1
grafana-datatable-panel v1.0.1

Thanks.

**Comment by rntbrgtt** [comment]
This is still not working on 1.0.2
Only integers are changing the font. 
@briangann  can you please re-open?

**Comment by briangann** [comment]
must have missed a commit :(

**Comment by scurvy-dog** [comment]
I just tested this plugin. Looks to do everything I need but, the table sizing is working only on columns with floating point values or timestamp. Columns with string values do not scale while those mentioned above do. This is with a new panel and all defaults except table sizing value set.
<img width="668" alt="Screen Shot 2021-07-31 at 5 21 05 PM" src="https://user-images.githubusercontent.com/13040225/127755290-ce84bdba-6a8c-4ac1-a869-31c1d8448c46.png">


Grafana 7.5.5
