### ISSUE TITLE
Assign dashboard variable to the field of table panel

### ISSUE THREAD

**Issue by Nelluru-Hemasree** [briangann/grafana-datatable-panel#106]
Hi,
Is there a way to assign dashboard variable to Rows per Page field in Datatable Options/Table Display
![Screenshot from 2020-06-24 13-28-01](https://user-images.githubusercontent.com/59244484/85519074-9008ee80-b61e-11ea-8344-da17d5629c99.png)
In my case rows is the dashboard variable. i want to assign that variable to rows per page so that rows per page updated whenever the dashboard variable is changed.
Thanks in advance.

**Comment by briangann** [comment]
This can be done, however:
the size of the panel will not work correctly if it exceeds the render space, not sure how to account for that.

**Comment by Nelluru-Hemasree** [comment]
> This can be done, however:
> the size of the panel will not work correctly if it exceeds the render space, not sure how to account for that.

can you tell me how to do that, assigning dashboard variable to the rows per page field.
