### ISSUE TITLE
Color cells/rows not working

### ISSUE THREAD

**Issue by clabeille** [briangann/grafana-datatable-panel#111]
Hello,

I've been playing around with this panel to try and get a dashboard for users to monitor file exchanges (the search function in particular is what drove me to it and I'm getting to something I really like).

I'd want to make use of the color function but it doesn't seem to work for me. I tried it on a column that has numeric values from the start and with a column that has numbers but in string format and each time putting a regex on the column, a number type, thresholds etc... But when I try to apply to the cell or value it doesn't do anything, and when I try to apply it to the row, I get an error and need to reload the dashboard without saving.

Grafana and the plugin are both in the latest versions.
Have you experienced similar issues ?

Thanks

**Comment by AvinKumar** [comment]
@clabeille : Yes even I am facing the same issue. 
My Grafana version is 6.7.3 and the Datatable Panel version is 1.0.1

-Avin

**Comment by vinhjs** [comment]
same issues

**Comment by contherad** [comment]
I was having the same issue. I began toggling the options off and found that removing "Row Numbers" fixed my issue.
