### ISSUE TITLE
Unable to add new panel

### ISSUE THREAD

**Issue by parthgajaria** [briangann/grafana-datatable-panel#113]
I just installed the grafana-datatable-panel plugin from https://grafana.com/grafana/plugins/briangann-datatable-panel/ by downloading the zip file. When I try to create a new dashboard, add a new panel and select "Datatable Panel" as the visualization, I receive the error "Panel plugin not found: briangann-datatable-panel". I'm running Grafana 6.2.5

**Comment by Adaox** [comment]
Did you also install the dependancies? 
Are you sure you extracted the zip to the correct directory?

I have found using the CLI is better for installing plugins

**Comment by parthgajaria** [comment]
> Did you also install the dependancies?
> Are you sure you extracted the zip to the correct directory?
> 
> I have found using the CLI is better for installing plugins

Where are the dependencies listed? The same behaviour happens when I try to install using the CLI

**Comment by parthgajaria** [comment]
This seems to work after upgrading to LAVA 7.1.5. It's incorrect to say this plugin is compatible with any LAVA 6.x and 7.x
