### ISSUE TITLE
Color text to match the RAG & additional threshold values

### ISSUE THREAD

**Issue by ganesh-s05** [briangann/grafana-datatable-panel#115]
Hi @briangann , 

I have got two scenarios where I would like you or other experts opinion on how to make this work. 

**Scenario 1:** 
I wanted to show RAG status just by coloring the cell without any text shown in there. As RAG status can be shown only for numeric values, the cell currently has some numbers. I would like to color these texts matching the cell bg color (Red/Amber/Green). By this, i can make the cell look only with color. I tried to reduce the font size to make it look small but that was also not feasible. Is there a way that i can achieve this? 

**Scenario 2:** 
Apart from the 3 conditions & colors for the thresholds, is there a way we can add a additional threshold? Currently, in Column style we define as, "50,75" & that takes care of Green,AMber,Red coloring. 
I would like to define as "40, 60,80" & color it as Green, Amber, <some_custom_color>, Red... Is it possible?

**Comment by briangann** [comment]
for scenario 1 that will have to be a new feature toggle
for scenario 2 that will have to be a new feature also - can likely leverage the new threshold model in grafana core to achieve this

**Comment by ganesh-s05** [comment]
Ok. Perfect. thank you for acknowleding @briangann ... I will await for the updates.
