### ISSUE TITLE
highlight search value

### ISSUE THREAD

**Issue by orena1** [briangann/grafana-datatable-panel#116]
Hi,
Can you please add an highlight of terms that were found in the searched, for example when I use the chrome browser search I'll get this:
![image](https://user-images.githubusercontent.com/8983713/88628060-fe295100-d0b5-11ea-8d90-68a2f0a27b67.png)

When I use the table plugin search, indeed it filter the lines that does not have the search term, but if will  be great if is also highlight the found term:
![image](https://user-images.githubusercontent.com/8983713/88628277-595b4380-d0b6-11ea-9e82-f30b5b9dfa0d.png)

thanks

**Comment by briangann** [comment]
good idea 👍

**Comment by briangann** [comment]
feature added in 1.0.3
