### ISSUE TITLE
Sorting doesn't work correctly

### ISSUE THREAD

**Issue by bryantlin** [briangann/grafana-datatable-panel#117]
Hi, I understand #104 is closed but I find the issue below. 

Original sort order: 

Column
-------------
1
9
12
82
13

After sorting (i.e. clicking the header "Column"), the data looks like:

Column
-------------
1
12
13
82
9

Does anyone run into the same problem? Or, am I missing something? 

Thanks!

**Comment by ccnoecker** [comment]
I am also having this issue with version 1.0.2 and Grafana 7, weirdly an old version (0.0.9) on another instance (Grafana 6) still works fine.

**Comment by briangann** [comment]
strange regression, will take a look

**Comment by welyss** [comment]
same problem,
and
I print the columnType with `console.log('wys:' + columnType + ',text:' + this.table.columns[i].text);` in file DatatableRenderer.ts:429
![image](https://user-images.githubusercontent.com/7651126/90600650-87e9bb80-e229-11ea-9e41-ab36709f9b8c.png)
**So I think the problem is why the columnType of the Number Column 'Value' is undefined, And if I set the Value's columnType to 'num', Then it works.**
hope helpful

**Comment by aerosadegh** [comment]
I have same problem.

**Comment by peterschristoph** [comment]
Same here, also the datatype does not matter.

- grafana @ 7.1.5
- briangann-datatable-panel @ 1.0.2


Problem:

- 9
- 5
- 3
- 2
- 2
- 2

Next page:
- 2
- 2
- 16
- 1

**Comment by ezerog** [comment]
It looks like sorting as string. This should be fixed asap.

**Comment by anthraxn8b** [comment]
Would be great to have this fixed soon... Your plugin is currently my only chance to get CSV in Excel dialect :-)

**Comment by hokiepokedad2** [comment]
I too have this problem.

**Comment by briangann** [comment]
in progress, need good sample data to work with to verify though :)

**Comment by anthraxn8b** [comment]
@briangann, use sample data with numbers ;-)

**Comment by aerosadegh** [comment]
> in progress, need good sample data to work with to verify though :)


id | num | Country
-- | -- | --
1 | 95 | Chile
2 | 883 | US
3 | 79 | Indonesia
4 | 754 | Brazil
5 | 75 | Romania
6 | 73 | Turkey
7 | 61 | South-Africa
8 | 56 | Iraq
9 | 55 | Italy
10 | 53 | Czechia

**Comment by ezerog** [comment]
any plan to resolve?

**Comment by briangann** [comment]
yes, will prioritize this one along with a couple others over the next few days, thanks!

**Comment by ezerog** [comment]
When will this be resolved? 😭
