### ISSUE TITLE
Column Searches dont match while panel search does

### ISSUE THREAD

**Issue by HeinDTP** [briangann/grafana-datatable-panel#118]
I have a table that contains a netstat output. One of the columns contains the state of the connection, when I search in the panel for "Listen" it works great, when i use the search added through the "Column Filters" option it does not match. Already upon typing L it says "No matching records found".

**Comment by clabeille** [comment]
I can confirm, I'm encountering the same issue. Tried matching uppercase/downcase too and it doesn't change anything. Only the main search works perfectly

**Comment by PT10** [comment]
Guys, please check if the column filter works fine after enabling global search. I also installed v1.0.1 first and then installed 1.0.2 and then enabled global search. It started working magically. Just check.

**Comment by HeinDTP** [comment]
Without global search it doesnt work at all, so I had it enabled already.

**Comment by joshuadino** [comment]
This issue still persists on v1.0.3 when I convert a column in timestamp to date format using column style. @briangann can you confirm?

**Comment by briangann** [comment]
will investigate, i'll be updating this soon so it will be react-based for future compatibility.
