### ISSUE TITLE
ISO 8601 Timestamp with time zone cannot be converted

### ISSUE THREAD

**Issue by Mr-Steel** [briangann/grafana-datatable-panel#119]
If you have a database field timestamp with timezone and the reulst is something like this "2020-07-31T22:00:00.772Z" it can't be properly overridden. If you select the field in the override dialog and as a Unit Date / YYYY-MM-DD HH:mm:ss nothing happens. In the previous table plugin this was the way to go. 
It would be great if this is working again.

**Comment by ZHumphries** [comment]
Can confirm when using Elastic Search as the data source.

**Comment by ZHumphries** [comment]
The column width hints also do not work when the time is in this format.
