### ISSUE TITLE
Hide columns does nor work

### ISSUE THREAD

**Issue by javierordonezojeda** [briangann/grafana-datatable-panel#12]

**Comment by javierordonezojeda** [comment]
When I set hiden column an error is displayed 

Thank you

**Comment by thibodux** [comment]
Can confirm the same issue for me with version 0.0.3 and grafana 4.5.x

**Comment by thibodux** [comment]
Could consider using `$.fn.dataTable.ext.errMode = 'throw';` as the default alert action. Just a naive suggestion.

**Comment by Nefariis** [comment]
can confirm on Grafana 4.6.x and version 0.0.3
![snip20171117_3](https://user-images.githubusercontent.com/26125080/32966203-e0aff29e-cb8d-11e7-9672-831f44835141.png)

**Comment by javierordonezojeda** [comment]
Thank you very much !!!!
