### ISSUE TITLE
TypeError:Cannot Create Property 'splitPattern' on number '0'

### ISSUE THREAD

**Issue by Ankitmay26** [briangann/grafana-datatable-panel#123]
Getting this error while using datatable panel in Grafana dashboard. Please help with the fix.

**Comment by bergerhag** [comment]
A workaround is to make sure every column has a matching style in "Column Styles", or a default one matching /.*/
This seems to be a bug in DataTableRenderer.ts which triggers when no style is matched for a column.

**Comment by bergerhag** [comment]
Added an extra check if column is undefined seems to do the trick for us. Row 41 in DatatableRenderer.ts
`  defaultCellFormatter(v: any, style: any, column: any, rowIndex: number) {
    if (v === null || v === void 0 || v === undefined || **column === undefined ||** column === null) {
      return '';
    }
`

**Comment by briangann** [comment]
fixed in 1.0.3!
