### ISSUE TITLE
error make new dasboard

### ISSUE THREAD

**Issue by HamidRezaEbrahimi** [briangann/grafana-datatable-panel#124]
i was able to use this panel but after after update to latest version  1.0.2 and grafana  7.1.5 show this error 

An unexpected error happened
TypeError: Cannot create property 'splitPattern' on number '0'

in t
    in t
    in div
    in div
    in div
    in div
    in div
    in t
    in t
    in t
    in div
    in Wa
    in div
    in on
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

please fix it 

tnx

**Comment by acarsercan** [comment]
Same here, running grafana 7.1.5

**Comment by Saroj-K-Panda** [comment]
Same error I am also getting, grafana 7.3.1

**Comment by briangann** [comment]
investigating this

**Comment by briangann** [comment]
fixed in new version 1.0.3
