### ISSUE TITLE
No signature verification for plugin

### ISSUE THREAD

**Issue by yoshpe** [briangann/grafana-datatable-panel#127]
When installing the plugin using command line or from [https://grafana.com/api/plugins/briangann-datatable-panel/versions/1.0.2/download](https://grafana.com/api/plugins/briangann-datatable-panel/versions/1.0.2/download), the plugin is unsigned (does not contain a MANIFEST.txt)
Unsigned plugins are not run by default since Grafana 6.7, 7.x

**Comment by briangann** [comment]
next release will be signed :)

**Comment by briangann** [comment]
1.0.3 is out and signed!
