### ISSUE TITLE
Nothing happens when I click on Alias, Width or Sort buttons

### ISSUE THREAD

**Issue by Krylanc3lo** [briangann/grafana-datatable-panel#13]
Hello,

Thanks a lot for this plugin, it is amazing.
It is maybe something you have already seen but nothing happens when I click on one of the new features. I checked the log and nothing neither.
I am using ElasticSearch or MySQL sources.

Do you know what might cause the issue ?

Thanks a lot,
Kry

**Comment by thibodux** [comment]
Same issue for me on Grafana 4.5.x with InfluxDB data sources

**Comment by danielkalen** [comment]
Duplicate of https://github.com/briangann/grafana-datatable-panel/issues/8
