### ISSUE TITLE
mysql datetime 

### ISSUE THREAD

**Issue by ivanpiffer** [briangann/grafana-datatable-panel#138]
Hi when I try to show my time field  (datetime format) from my MariaDB what I see is a "1.62 Tri" value repeated on every record :(
What's wrong?
On the original Table Panel from grafana the result is correct ... for example "2021-04-02 09:09:55" ... the same on your datatable panel is "1.62 Tri"

grafana-server -v
Version 7.5.1 (commit: 4dffb875cf, branch: HEAD)

installed plugins:
briangann-datatable-panel @ 1.0.3

MariaDB
ENGINE=MyISAM DEFAULT CHARSET=utf8

**Comment by jinx17** [comment]
I have the same issue, but with flux query table
