### ISSUE TITLE
bug: cell colour coding does not consider units

### ISSUE THREAD

**Issue by atos-edward-stewart** [briangann/grafana-datatable-panel#139]
Feeding Grafana with Prometheus and visualising with datatable panel.
Some Grafana units, eg Data / Gigabytes automatically perform a human readable conversion, eg from GB to TB to PB when they are displayed.

If you create a datatable with a column style rule against a column with a unit of gigabytes (for example), the thresholds you enter are used to colour code against the rendered output text, not the actual data value.  

eg:
![image](https://user-images.githubusercontent.com/44804584/115867159-a0eae200-a432-11eb-9b4e-e0d4fa25ccb9.png)

This is where we have a red -> orange -> green with reshold 0, 10
The 1.05TB is firing orange because it's between 0 and 10
The 100GB is firing green because it's over 10
the 17.11TB is firing green because it's also over 10

I would expect 1.05TB to fire green because it's actualy 1.05*1024.

This makes the data misleading.

Instead the actual raw data value should be used for colour coding, not the rendered value which may change units for readability.

**Comment by HenningRath** [comment]
Hi,

I believe getCellColors is incorrectly using cellData (which is formattedData). After changing as follows formatting is correct:
@@ -596,7 +596,7 @@ export class DatatableRenderer {
           //    1) Cell coloring is enabled, the above row color is skipped
           //    2) RowColumn is enabled, the above row color is process, but we also
           //    set the cell colors individually
-          const colorData = _this.getCellColors(_this.colorState, actualColumn, cellData);
+          const colorData = _this.getCellColors(_this.colorState, actualColumn, String(_this.table.rows[row][col]));
           if (!colorData) {
             return;
           }
