### ISSUE TITLE
Sorting on TableData "number" column does alphabet sorting, not number sorting

### ISSUE THREAD

**Issue by jengstro2** [briangann/grafana-datatable-panel#14]
Great DataTable panel with search function, what is ultimate feature compared to standard Grafana plugin offering. However, the sorting does not work on number columns. It seems to do alphabet sorting. The Grafana "Table" panel,  sorting works.

Here is snip of JSON table data what is returned from my backend,
[{
	"type": "table",
	"columns": [{
		"text": "ITEMID",
		"type": "string"
	}, {
		"text": "PRODGRP2_NAME",
		"type": "string"
	}, {
		"text": "NAME1",
		"type": "string"
	}, {
		"text": "STOCKLOC",
		"type": "string"
	}, {
		"text": "UNIT",
		"type": "string"
	}, {
		"text": "QTY",
		"type": "number"
	}, {
		"text": "LOCPRICE",
		"type": "number"
	}, {
		"text": "TOTALVALUE",
		"type": "number"
	}],
	"rows": [
		["501816-M39-280", "Bolts", "M39x280A193-B7/2HStud bolt with two hexagonal nuts", "blah", "pcs", 165.0, 10.43, 1720.95],
....
...

**Comment by tiitpaananen** [comment]
would love to get this fixed

**Comment by cosote** [comment]
Had the same issue and fixed it in a fork of danielkalen: https://github.com/cosote/grafana-datatable-panel/tree/feature/fix-sorting
I've added also some other things, like search highlighting, that could be merged...
@briangann Keep up this great plugin - Cheers, Cosote.

**Comment by jim256** [comment]
@briangann just wanted to touch base and see what your thoughts were of merging cosotes PR?
