### ISSUE TITLE
Question: How to make available in "Visualizations" in Grafana 8

### ISSUE THREAD

**Issue by jim256** [briangann/grafana-datatable-panel#147]
If I have the plugin successfully installed (and can verify that by looking in "Plugins"), I'm unable to see it under the "Visualizations" section when creating a new panel.

This is probably a really dumb question, but what do I need to do in order to enable me to actually use the visualization? It appears by default in the list on 7.5.9, but not on 8.0.3.

**Comment by 1270514689** [comment]
@jim256 are you solved the problem ?

**Comment by VolkrB** [comment]
+1

**Comment by novotnyjan426** [comment]
+1
