### ISSUE TITLE
update to grafana 8.x.x

### ISSUE THREAD

**Issue by 1270514689** [briangann/grafana-datatable-panel#152]

**Comment by tsgit** [comment]
seems to work with grafana 8.5.9, however the layout changed in grafana 9.1.1 and fewer rows are displayed and the pagination buttons are not visible.  Can we expect an  update for grafana 9?

**Comment by briangann** [comment]
yes, there will be an update to address 9.x issues, there are some api changes that are likely causing problems.

**Comment by SoniXtrA** [comment]
hello @briangann 

Any news, any updates ? 
Best regards !!!

**Comment by briangann** [comment]
new release v1.0.4 should address these issues, I checked v8/v9/v10 and it looks correct. let me know if you run into any problems with it.

next release with be a port to react!
