### ISSUE TITLE
root url issue

### ISSUE THREAD

**Issue by sergeyarl** [briangann/grafana-datatable-panel#16]
I have the following setting in my grafana.ini 

`root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana`

That means that my grafana url looks like `http://myserver/grafana`

Hoever when I try to use datatable-panel plugin I see the following in  js console of my browser:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.dataTables.min.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (datatable-dark.css, line 0)
[Error] Potentially unhandled rejection [3] (SystemJS) Error loading CSS file.
        onerror
        Error loading http://myserver/public/plugins/briangann-datatable-panel/libs/datatables.net-dt/css/jquery.dataTables.min.css!http://myserver/grafana/public/app/core/utils/css_loader.js
        (anonymous function) (boot.4aeac494.js:5:27838)
        f (boot.4aeac494.js:5:27434)
        i (boot.4aeac494.js:5:27723)
[Error] Potentially unhandled rejection [6] (SystemJS) Error loading CSS file.
        onerror
        Error loading http://myserver/public/plugins/briangann-datatable-panel/css/datatable-dark.css!http://myserver/grafana/public/app/core/utils/css_loader.js
        (anonymous function) (boot.4aeac494.js:5:27838)
        f (boot.4aeac494.js:5:27434)
        i (boot.4aeac494.js:5:27723)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (query, line 0)

```

Seems like Grafana Datatable Panel ignores grafana root_url setting. 

Can you please help me solve this issue? 

Thank you! 

Regards,
Sergey

**Comment by briangann** [comment]
Let me try this out with a sub-path and see what is causing it.  It should be using a relative path.

**Comment by sergeyarl** [comment]
Thank you for the answer. 

I'm using nginx as HTTP frontend. And the following  vhost config : 

```
server {
  listen       80;
  server_name  _;

  root       /path/to/my/main/site;

  location / {
    index      index.php;
  }

  location /grafana {
    proxy_pass         http://localhost:3000;
    rewrite  ^/grafana/(.*)  /$1 break;
    proxy_set_header   Host $host;
    proxy_redirect                off;
  }

}
```

**Comment by briangann** [comment]
I have the same setup now and see the problem, I'll have a fix for it shortly.

**Comment by briangann** [comment]
The fix is in the 20171209_issue16 branch.  I'll merge and have it updated on grafana.com.

I tested the plugin on both a "top-level" instance and one with a subpath, and they work as expected.  I better check my other plugins for this problem too...

Thanks!

Brian

**Comment by sergeyarl** [comment]
Thank you!

**Comment by Kumaravel2904** [comment]
I am still facing the issue, can you please help how to install the plugin using the latest code. Because grafana-cli plugins install briangann-datatable-panel does not help
