### ISSUE TITLE
Value Mappings - Feature Sugestion 

### ISSUE THREAD

**Issue by lucioaquino** [briangann/grafana-datatable-panel#18]
Hello 

Would bevery apreciate to have a feature to map values to names or strings like in single stat panel , i have a big panel with hundred of alerts and a dashboard with a table solve this problem .

Make a huge diference.

![image](https://user-images.githubusercontent.com/18651504/34910105-944cf1d8-f895-11e7-8493-8f392a61f46d.png)

Feature like this 

![image](https://user-images.githubusercontent.com/18651504/34910120-c0d4c6cc-f895-11e7-9a10-a1fcf456a710.png)

**Comment by briangann** [comment]
sounds good to me, will implement it

**Comment by briangann** [comment]
available in v0.0.7
