### ISSUE TITLE
Update to support Grafana v5.0 

### ISSUE THREAD

**Issue by torkelo** [briangann/grafana-datatable-panel#20]
This panel tries to access the height via the row, this really the best/preferred way to do it (hence it does not work v5).

Just use ctrl.height (this.height) in the panel if you need the panel height. 

https://github.com/briangann/grafana-datatable-panel/blob/master/src/ctrl.js#L397

**Comment by briangann** [comment]
Fixed and merged, datatable is working in both v4 and v5 now.

Thanks!

Brian
