### ISSUE TITLE
[Feature request] Add the ability to use a cell's content to generate its hyperlink.

### ISSUE THREAD

**Issue by jonstout** [briangann/grafana-datatable-panel#23]
It's currently possible to use `$__cell` in the url input box as a way to use a cell's content to generate its hyperlink. In some cases however, it may be desirable to use only a portion of the content. It may also be desirable to use separate portions of the cell's content in separate portions of the url.

I propose adding a Parameterization input which takes a regular expression which will be used to split the cells content. After splitting we could provide variables similar to the `$__cell_n` variables.

Copied from: https://github.com/grafana/grafana/issues/11066

If it helps, I created an implementation once before for the core table panel. It used a 'Parameterize by' input box that took a regex to split the string. Once split the `$__pattern_n` variables could be used in the Url input box to generate the url.

As an example, we have the target name set as a comma separated string. By breaking up the parts we're able to link each row to a separate dashboard and pre-populate the required template variables.

![screen shot 2018-03-28 at 1 36 40 pm](https://user-images.githubusercontent.com/173253/38046243-2a88518e-328d-11e8-8065-d6179baa5d73.png)

![screen shot 2018-03-28 at 1 28 29 pm](https://user-images.githubusercontent.com/173253/38045888-20e0d7c4-328c-11e8-9f9a-415c36ca8a69.png)

Original: https://github.com/grafana/grafana/pull/11068

**Comment by briangann** [comment]
merged, but keeping this open so the documentation can be updated
