### ISSUE TITLE
Draw on windows resize

### ISSUE THREAD

**Issue by CorentinDy** [briangann/grafana-datatable-panel#24]
Hi,
i'm using your datatable plugin on grafana.

I'm trying to use it to edit some data (i know grafana is not supposed to be used like this but i'm not the one who asked for this ).

Every time i resize my browser's windows, the datatable is being reloaded so if I have some textarea , the data will be change by the one loaded by the datatable at first call on database.

Any way to help me with those ? 

Thx

**Comment by briangann** [comment]
that's a function of grafana calling refresh.  I'm not sure how a write-back through the datatable would work, it's not something I've tried.  The datasource would have to support the write operation, and I don't see an option for that in datasources.

**Comment by briangann** [comment]
would adding an option for disabling refresh work here? this is an edge case that i haven't seen before

**Comment by CorentinDy** [comment]
Sorry for leaving the issue as is but I left the project wich has this problem.
I'll try to find if we had a fix for this or no ;)
