### ISSUE TITLE
Datatable panel is not showing in dasbboard after successful installation also

### ISSUE THREAD

**Issue by anilkumar-sannamuri** [briangann/grafana-datatable-panel#29]
We tried the following command to install datatable panel
```grafana-cli plugins install briangann-datatable-panel```, but we couldn’t able to see in the datatable panel in the dashboard after performing the command. Could you please help us. Thanks!

**Comment by mohanraj1939** [comment]
What OS are you using?

**Comment by anilkumar-sannamuri** [comment]
No @mohanraj1939. After restarting the grafana dashboard, issue is resolved. Thank you!

**Comment by Saroj-K-Panda** [comment]
Hi,
I am getting an issue as "unsigned" after installing the plugin. Can anyone pls help. Thanks in advance.

**Comment by briangann** [comment]
the new release 1.0.3 fixes the signing issue, thanks!

**Comment by Saroj-K-Panda** [comment]
> the new release 1.0.3 fixes the signing issue, thanks!

Thank you. It was resolved. !
