### ISSUE TITLE
"Clickable" Not creating correct link

### ISSUE THREAD

**Issue by ghost** [briangann/grafana-datatable-panel#30]
Grafana v5.0.3
Datatable Panel v0.0.6

Column Set Up:
![image](https://user-images.githubusercontent.com/26387530/38743525-2f614c54-3f37-11e8-95b6-f37cb4b48b01.png)

Link on Hover:

![image](https://user-images.githubusercontent.com/26387530/38743558-4e8935f6-3f37-11e8-94d2-9841916677ce.png)
![image](https://user-images.githubusercontent.com/26387530/38743592-670ebc7c-3f37-11e8-9a35-45cf2df2f549.png)

Can I add data from other columns like the vanilla Grafana Table too. e.g $__cell_6?

**Comment by 999chris** [comment]
Have since found out the "Column" field needs to match the name of the column it's being applied to. This is not clear.

**Comment by briangann** [comment]
I'll update the docs, good catch :)

**Comment by parangatshukla** [comment]
Does Datatable Panel have the ability to access data from other columns like Grafana table does? Tried using $__cell_x syntax, doesn't work

**Comment by bbarclay** [comment]
Me too. I tried putting http://url.com:3000/d/48kP922mz/variant?orgId=1&var-Sites=$_cell

and it doesn't work. I put that in the url box and it doesn't work.

**Comment by bbarclay** [comment]
It defaults to http://url.com:3000/$_cell

**Comment by briangann** [comment]
recent PR implemented this, will be in 0.0.7

**Comment by gitbtasel** [comment]
Hi Brian, 

Grafana.com still has version 0.0.6 of the plugin hence it is missing this fix for table cell (__cell)/link creation. We are using the Datatable plugin and need to create links out of values stored in cells. Do you have an estimate as to when 0.0.7 (rpm) will be added to grafana.com? Thank you.
