### ISSUE TITLE
Stat summary under data table

### ISSUE THREAD

**Issue by bgruenefeld** [briangann/grafana-datatable-panel#32]
Hi,

data table seems to be a very nice table plugin for grafana with many useful features.

I wonder if it would be possible to add a stats summary below the data table itself, maybe as a second table below.
 Something like the following picture:
![2018_04_19_19_31_52_grafana_](https://user-images.githubusercontent.com/10279112/39008537-3f6478b6-4409-11e8-8b8d-077b365c3410.png)

As far as i see, there is a model for the table data, is it possible to enhance the model to fullfill the above idea?

kind regards
Bernd

**Comment by briangann** [comment]
that can be added - i'll have to setup a roadmap for this plugin :)
