### ISSUE TITLE
Unable to see Show No. of Entries

### ISSUE THREAD

**Issue by mohanraj1939** [briangann/grafana-datatable-panel#34]
Hi,

This is a great plugin, search& no. of entries in dashboard itself is a great future in this plugin even grafana table doesn't have.

I'm trying for below screenshot:
![datatable-threshold-row](https://user-images.githubusercontent.com/33648564/39689123-28cb4f06-51f3-11e8-9ac8-4d14c6d6d3d1.png)

I obtained:
![panel](https://user-images.githubusercontent.com/33648564/39689145-42517978-51f3-11e8-9ed0-8d8c17060749.PNG)

**Comment by briangann** [comment]
that may be a light-style bug, let me check into it.
