### ISSUE TITLE
Is it possible to pass and render html elements ?

### ISSUE THREAD

**Issue by a1ex4** [briangann/grafana-datatable-panel#35]
Hi, I'm trying to pass HTML elements (a button, list...) in one of my columns, I pass the code as "string".

Although the HTML tags are escaped so the cells only contain text. Is the plugin using Grafana's methods ? Escaping HTML was added here : https://github.com/grafana/grafana/issues/4596#issuecomment-206778698

Thank you very much for your work and help ! :)

**Comment by briangann** [comment]
i'll add this feature, thanks!

**Comment by likeitneverwentaway** [comment]
Awesome news ! Although the "sanitization" happens with the default table renderer, not sure if this helps but to disable this sanitization I commented out everything that was replacing "<" with "&lt;" for example.

Thanks! 👍

**Comment by krswin** [comment]
@briangann when this feature will be added? thanks
