### ISSUE TITLE
"Merge Multiple Queries per Table" support

### ISSUE THREAD

**Issue by vvxxsz00** [briangann/grafana-datatable-panel#36]
Greetings
is there any possibility to implement compatibility with this standard "Table" panel feature?
http://docs.grafana.org/features/panels/table_panel/#merge-multiple-queries-per-table

As far as I can see from DevTools datatable panel sends only one query (the first in a row) and ignores others.

Thank you in advance

P.S. InfluxDB is used as the data-source

**Comment by briangann** [comment]
i'll see about pulling in this functionality

**Comment by infa-kparida** [comment]
+1
