### ISSUE TITLE
[Enhancement] Increase the Width of the Search Bar

### ISSUE THREAD

**Issue by AurelienAtAvelia** [briangann/grafana-datatable-panel#37]
It would be nice to increase the width of the search bar to clearly see the entire search criteria. Indeed, most of time users use multiple long keywords and with the actual width it is not possible to clearly see the entire search criteria. Ideally the size of the search bar should be the same as the table.

**Comment by briangann** [comment]
sounds good, i'll add a width option for in the datatables options section
