### ISSUE TITLE
Pannel Options

### ISSUE THREAD

**Issue by adriaand007** [briangann/grafana-datatable-panel#38]
Some of the DataTable options is not working
![image](https://user-images.githubusercontent.com/13329360/47136888-531b1f00-d2b5-11e8-9fa5-5a6a37f0fd1e.png)
these options is not working if I click on them nothing happens
If not avilble then gray them out

**Comment by ludik0** [comment]
Same Problem over here with Datatable Panel v0.0.6 and Grafana v5.2.3 

In the Readme it says that v5 is not supported, but in the commits I see Bugfixes for v5. 

Should this Work with Grafana v5 ?

**Comment by briangann** [comment]
investigating, that's odd
