### ISSUE TITLE
Rendering the paging elements

### ISSUE THREAD

**Issue by ludik0** [briangann/grafana-datatable-panel#39]
Hi,

I have a Problem with the Plugin. If a linebreak is needed to display the data, the rendering of the paging elements fails or they are not visible. See the two screenshots.

![image](https://user-images.githubusercontent.com/25457867/47285660-06548280-d5ec-11e8-92f2-03f1c20f7928.png)

![image](https://user-images.githubusercontent.com/25457867/47285730-4156b600-d5ec-11e8-8dc1-f6880d650da0.png)

Is there a way to fix this using the options? I'm using version 0.0.6 and Grafana version 5.2.3. 

Thank you for your time !

**Comment by briangann** [comment]
let me check into this, might be a bug in datatables.net
