### ISSUE TITLE
Column order fail

### ISSUE THREAD

**Issue by rogercorrea** [briangann/grafana-datatable-panel#4]
Please,

I did try use Datatable in Grafana but I found error in the order column.
I don't found as add column order registers and also doesn't work if I try use "ORDER BY data DESC" in my SQL sintax.

What I have to do?

**Comment by briangann** [comment]
The column ordering/aliasing/widths functionality has only been tested with JSON/table output where you select the columns.  I'll check the other types and fix those before publishing to grafana.com.

If you're cloning from here expect a fair number of updates over the next couple of days for bugfixes in the new code.

Thanks!

Brian

**Comment by rogercorrea** [comment]
Thanks, @briangann !
I also did see that not is possible use the stateSave option. The DataTables have the function and whitout her don't allow use the order and filters when I use the auto-refresh function.

**Comment by briangann** [comment]
That's correct - I'm looking at how to preserve that within the panel too.  The savestate is a "cookie" and doesn't seem to stick to the panel.

**Comment by biro11** [comment]
Hello, I have similar issue. I am trying to sort table data according to timestamp. I have set up column style for my date field with format "DD.MM.YYYY HH:mm:ss". After that data are sorted by alphabet and numbers. The field expresses date, not only pure string. 
How can I sort by date? Thanks!

![image](https://user-images.githubusercontent.com/5763101/28529323-8b4a0572-7090-11e7-9619-085592ab54bb.png)

**Comment by briangann** [comment]
I think this needs to change the timestamp sort to be by the real value (in seconds) vs the text displayed, that's the only way to ensure it is linear according to time. It's currently sorting by the text that is reformatted.

**Comment by tmeinlschmidt** [comment]
would be fine to follow default ordering inside the data (like order by) and do not force it's own (from datatable). btw - I'm missing 'default' sorting column, when we're talking about sorting.

**Comment by Ssiws** [comment]
Hello !
Any news on that ? Datatables is a great grafana plugin but hard to use in production because of this issue.
Thanks !

**Comment by briangann** [comment]
I'll take a look at this today along with the other issues and get it working properly.

Thanks!

**Comment by githubkatten** [comment]
> I'll take a look at this today along with the other issues and get it working properly.
> 
> Thanks!

Hi!
We´re using this nice plugin so it would be great if this order by is done in the milestone 0.0.7
Thanks!

**Comment by srounet** [comment]
*bump* having the exact same issue, with latest plugin version (**v0.0.6**) and grafana (**v6.0.2 (commit: 3f4c2e7)**).

Also i would like to say that clicking onto "**Column Sorting (applied top to bottom)**" > "**Add Rule**" does not produce anything (it won't even display a field where I should type in column name).

This plugin is very nice (thank you for supporting it), and is a must have replacement to standard table plugin. Having the ordering feature working is a must.

I hope you will find time to work on it soon.

**Comment by giovannirco** [comment]
Any news on this? I see it was removed from the milestone

**Comment by briangann** [comment]
review all issues and making a plan :)
