### ISSUE TITLE
PDF / EXCEL export

### ISSUE THREAD

**Issue by cicciopizza** [briangann/grafana-datatable-panel#40]
Version 5.3.2 of grafana
Plugin v0.0.6

I can not find the option to export to Excel / PDF
I see in the release notes that from version 0.03 it was a new feature
![selezione_058](https://user-images.githubusercontent.com/26459829/47995918-29585980-e0f7-11e8-9538-67d38571569a.png)

**Comment by briangann** [comment]
looks like the icon for exporting is missing, will fix asap

**Comment by grenzbotin** [comment]
Hi @briangann,
do you know when this might get fixed? (Tested in v0.0.7 and looks like it is still missing)
