### ISSUE TITLE
DataTables warning when Time column is hidden

### ISSUE THREAD

**Issue by FdeFabricio** [briangann/grafana-datatable-panel#43]
Whenever I set the Time column type as Hidden...

![](https://user-images.githubusercontent.com/1853854/48413039-8ffbf980-e72d-11e8-9862-47979dbe4395.png)

I get this error, that shows up constantly

![](https://user-images.githubusercontent.com/1853854/48413054-a0ac6f80-e72d-11e8-9f2e-e53483156f49.png)

**Comment by briangann** [comment]
I have seen this before, will investigate it.
