### ISSUE TITLE
Option for pagination + scrolling

### ISSUE THREAD

**Issue by saurabh3896** [briangann/grafana-datatable-panel#45]
Is there any way to enable both pagination and scroll feature? Suppose I set the number of rows to 100 on one page, but since there is no scrolling available, it's impossible to go to the bottom of the page.

**Comment by saurabh3896** [comment]
Never mind, I figured it out. I commented this block:
     if (this.panel.scroll) {
         tableOptions.paging = false;
         tableOptions.scrollY = panelHeight;
      } else {
         tableOptions.paging = true;
         tableOptions.pagingType = this.panel.datatablePagingType;
      }
, added the field `scrollY: panelHeight`` and set `scollCollapse` to `true`.

**Comment by briangann** [comment]
this would be a good feature to add, opening up the issue :)

**Comment by briangann** [comment]
targeted for the 1/28 release, looks easy to add.

**Comment by saurabh3896** [comment]
@briangann In case we need to migrate a panel from the default `table-panel` to `grafana-datatable-panel` with data and datasources intact, is there any way to do it (except manually modifying the `type` field in the panel JSON)?

**Comment by briangann** [comment]
fixed in v0.0.7, please double check though!
