### ISSUE TITLE
Publish plugin to Grafananet

### ISSUE THREAD

**Issue by Atem18** [briangann/grafana-datatable-panel#46]
Hi,

Do you think it's posible to publish the plugin to Grafananet ?

That way it would be easier to update it.

Thanks in advance.

**Comment by briangann** [comment]
it's available here:

https://grafana.com/plugins/briangann-datatable-panel

it can also be installed with the grafana cli.

**Comment by Atem18** [comment]
Indeed, thanks a lot.
