### ISSUE TITLE
How  to  deal with this problem ,the tool will be  stucked when the data exceeds 10000?

### ISSUE THREAD

**Issue by DFX339** [briangann/grafana-datatable-panel#47]
Dear developers:
          I was used this plugin to show table data ,it is so cool and beautiful.
but when I wan to show more data , issue is comming. Whole tool came so stucked, the data loading need about 7 seconds, but I should spend lots of time to wait it response. Any Button or Event need wait long time.     If you have an better plan to slove this,Please touch me .
Thank you very much.

**Comment by briangann** [comment]
I'll explore async dataloading which may help when the plugin can be non-responsive when loading large sets.

**Comment by thda** [comment]
For postgresql/mysql/clickhouse/sql server datasources, adding variables for limit/offset clause and re-running the data fetching routine when clicking on next would be a good start.

Also, if the csv export functionality could remove that clause and stream the data it would allow downloading huge files without hanging the browser.
