### ISSUE TITLE
paging  enabled not work

### ISSUE THREAD

**Issue by ricoisme** [briangann/grafana-datatable-panel#48]
Hi ,

I have enabled paging option but not working in grafana V5.4.3
![image](https://user-images.githubusercontent.com/17023972/52495494-cac9dc80-2c0b-11e9-8b58-cc8807adab55.png)

I only saw scrolling mode always.
![image](https://user-images.githubusercontent.com/17023972/52495598-301dcd80-2c0c-11e9-8cfc-34b44e9e6c1b.png)

how can I do to solve this problem?

Thanks

**Comment by yiip87** [comment]
Hey,

looks like your issue could be solved by #45
