### ISSUE TITLE
Scroll enabled not work Grafana v6.0.0

### ISSUE THREAD

**Issue by almeidarfael** [briangann/grafana-datatable-panel#49]
Scroll enabled not work Grafana v6.0.0

**Comment by lingfish** [comment]
You have progress... I can't even see it as a panel available to add.

**Comment by almeidarfael** [comment]
![grafana](https://user-images.githubusercontent.com/48135238/54042613-4d14d480-41a9-11e9-84bb-206b217c3dcc.jpg)

**Comment by almeidarfael** [comment]
![InkedGRAFANA_LI](https://user-images.githubusercontent.com/48135238/54119580-736a8800-43d4-11e9-942d-78cb0f9d4ee6.jpg)

**Comment by briangann** [comment]
fixed in v0.0.7
