### ISSUE TITLE
Forming a grid of single-stats

### ISSUE THREAD

**Issue by cubranic** [briangann/grafana-datatable-panel#5]
Given a metric with two dimensions, can I use this panel to show a table where columns are created from the values of one dimension, rows from the values the other, and the value of each cell is the current value (or aggregation) of the metric with that cell's coordinates?

As a real-world example, let's say I have a Prometheus data source. It provides the "up" metric, with labels "job" and "instance". I'd like to arrange the values of "up" into a grid for each job/instance combination.

**Comment by briangann** [comment]
That's a great scenario and something that could be implemented. I can see using this myself.

**Comment by cubranic** [comment]
If you can give me some pointers on the necessary changes, maybe I can have a go at implementing it.
