### ISSUE TITLE
Threshold have effect over the unit value and not the original value.

### ISSUE THREAD

**Issue by ceinmart** [briangann/grafana-datatable-panel#54]
When set the Unit to duration(s) and put any threshold value , the panel check over the unit value recalculated and not over the original value. 
Since this unit can show in multiple levels (seconds, minutes, hours) the threshold isn't check correctly and then do not change the colors correctly. 

Using grafana 6.x .

**Comment by Adaox** [comment]
I am also having similar issues with Threshold values not displaying 

Specifically, when using Date & Time -> From Now
and
Misc -> Percent (0.0-1.0)

Interestingly enough, with RegEx "/.*/" both From Now and Percent will change colors... however I need different thresholds per column. 

Using Grafana 7.1.3 and DataTable 1.0.2
![Screenshot (15)](https://user-images.githubusercontent.com/34901524/89613889-492f2b00-d851-11ea-8f9f-eb9a3fc0ab51.png)
