### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by JBleijenberg** [briangann/grafana-datatable-panel#56]
Not really an issue, but more of a question.

Is this project abandoned and should i move on to something else?
It's clearly not working as intended in Grafana 6 and the last commit is months ago.

**Comment by briangann** [comment]
Not abandoned at all, definitely welcome some help though!

I'll check out what is going on in v6.

**Comment by briangann** [comment]
tested in v6, is working for me. reopen if you have a bug :)
