### ISSUE TITLE
Panel does not load +2500 lines

### ISSUE THREAD

**Issue by exit2escritical** [briangann/grafana-datatable-panel#57]
Hi there,

I'm using this panel to list a number of hosts and it's ip_address that come from 4 different Mysql databases so I can use the Search text that comes with the pannel.
On the Metrics tab:
- Datasource: Mixed
- Queries are the same just pointing out to the different mysql dbs I have.

Results are showed in a table, but limited :(
![image](https://user-images.githubusercontent.com/26905699/59091669-1c5f4b00-8910-11e9-9bd7-490ba437e8f5.png)
When I have more than 8000 lines...
:(

Why is this happening?
Any help would be appreciate.
Thanks in advance,

Alba.

**Comment by exit2escritical** [comment]
Mmm, I know what's going on.
Even though I have 4 queries in the metric tab, the panel is only showing one :(

Is there a way to JOIN the results of the 4 queries in order to be showned into the table?

Thanks a lot.

**Comment by briangann** [comment]
It's designed for just one query, not sure how to mix multiple queries together cleanly.

Suggestions welcome :)

**Comment by exit2escritical** [comment]
I see... 
In my particular case, the results from querying different DBs have same columns and same type of data...so it's only adding the results together in the same table...

![image](https://user-images.githubusercontent.com/26905699/59181579-fb913280-8b67-11e9-974d-7412662931a8.png)


You could give the option to change between same type of datasources (only influx, only mysql...) but the query has to be clonned, that way you know the results to the different dbs are going to match.

Do you know if there's any other pannel I can use to show what I want?
The results added together in a table from the same query to different databases with a Search box.

Thanks a lot for your interest!

**Comment by briangann** [comment]
I'm not aware of another plugin that can do this.
Now that I've had some time to think - the table could provide a column indicating the query it came from (which would be optional).  Sorting would auto-mix the data, which makes this not as difficult as I first thought.

**Comment by exit2escritical** [comment]
So...do you think you'll have time to implement multiple-query option for your datatable-panel any time soon?
