### ISSUE TITLE
Adding action buttons in datatable panel

### ISSUE THREAD

**Issue by akidatawaka** [briangann/grafana-datatable-panel#59]
Hi Brian, 

I would like to ask how to add action buttons (view, edit, delete) for each record  in datatable panel like in the image below. 

if a user click View then I would like to perform a function
if a user click Edit then I would like to perform a function
if a user click Delete then I would like to perform a function

Thank you in advance Brian!

![image](https://user-images.githubusercontent.com/15179647/60233378-4336ee80-98ca-11e9-97f0-35c20569e436.png)

**Comment by fpanwaskar** [comment]
We have a similar requirement, I was thinking of row actions that can be accessed via a context menu.

Users could define an array of rowActions.

A single action definition would look like:
{
    title: 'Delete'
    hide: (row) => // returns true to hide action
    mapRow: (row) => // returns row data to be supplied to action 
    action: (row) => // request to datasource
}

I'm new to grafana and not sure how feasible implementing this is.

Would there be interest in adding a feature like this to the table?
If so I would like to contribute.
