### ISSUE TITLE
Time Series 

### ISSUE THREAD

**Issue by shayan90** [briangann/grafana-datatable-panel#6]
Hey,

Thanks for the great work on the Datatable panel looks amazing. I am facing some issues on time series updates on the panel, it seems it does not listen to change properly. any work around ?

**Comment by briangann** [comment]
I'll have the fix for this in the next release.

**Comment by briangann** [comment]
v0.0.3 has the fix for this problem included, update and let me know if it works for you.

**Comment by briangann** [comment]
closing as this was fixed
