### ISSUE TITLE
this.stringToJsRegex error after latest update

### ISSUE THREAD

**Issue by tayfuncakicier** [briangann/grafana-datatable-panel#63]
Hello @briangann,

I have updated our grafana plugins last week and our datatable panel using dashboards do not work after that. We get the error below. How can we solve this issue?

**TypeError: this.stringToJsRegex is not a function
    at Array.t.defaultCellFormatter (http://our_server_url/public/plugins/briangann-datatable-panel/module.js:23:4377)**

**Comment by peterhpchen** [comment]
I get this error, too. You can try add Column Styles below:

![image](https://user-images.githubusercontent.com/6873700/62512804-13292680-b84c-11e9-99ba-fe5a6da8303d.png)

It resolves my problem.

**Comment by tayfuncakicier** [comment]
> I get this error, too. You can try add Column Styles below:
> 
> ![image](https://user-images.githubusercontent.com/6873700/62512804-13292680-b84c-11e9-99ba-fe5a6da8303d.png)
> 
> It resolves my problem.

Thnx @peterhpchen I have added new column style to all dashboards and all errors are gone.
