### ISSUE TITLE
Filter by column

### ISSUE THREAD

**Issue by anthraxn8b** [briangann/grafana-datatable-panel#66]
Hi!

I would like to filter the table content by column. As far as I can see there is the possibility to filter by the table-global "search" field - but not by column. Correct?

So I would like to have a search field for each column.

If this is already possible, please tell me how :-)
THX in advance!

**Comment by holgerbrandl** [comment]
Same here, I have worked with https://rstudio.github.io/DT/ a lot, and column features are one of the most useful features of the datatable library.
