### ISSUE TITLE
How to scroll the table headers with table data?

### ISSUE THREAD

**Issue by leonhilton** [briangann/grafana-datatable-panel#7]
Hi Brian,

I'm new to Grafana and am trying to use the native Table as well as your Datatable Panel.
My table has many columns (wider than panel). While I can use your scrollbar to scroll data left/right, the header row does not track with the data.

How can I get the header to scroll?

Thanks!

**Comment by briangann** [comment]
Let me look into this, I haven't tried doing that.

**Comment by briangann** [comment]
I'll have a fix for this in the next release, that was an easy change :)

**Comment by leonhilton** [comment]
Excellent!
When's the next release? :)

**Comment by briangann** [comment]
This is included in v0.0.4
