### ISSUE TITLE
Grafana upgrade from 6.0.0 to 6.4.x broke datatable plugin

### ISSUE THREAD

**Issue by satishdotpatel** [briangann/grafana-datatable-panel#72]
I have opened issue to grafana but i should mention here: https://github.com/grafana/grafana/issues/19323

**Comment by societymartingale** [comment]
I am also experiencing this issue. After upgrading to Grafana v6.4, the datatables are broken and show "TypeError: Cannot read property 'length' of undefined."

I ended up reverting Grafana to prior version. Hoping this will be fixed soon, as it is preventing me from upgrading to Grafana v6.4.

**Comment by societymartingale** [comment]
Here are screenshots originally posted by Satish: https://community.grafana.com/t/grafana-upgrade-from-6-0-0-to-grafana-6-4-0-beta1-broke-datatable-panel-plugin/21297

**Comment by societymartingale** [comment]
Just adding some more detail:
Grafana version: 6.4.1
Datatable version: 0.0.9

Error output from browser console:
Panel data error: TypeError: Cannot read property 'length' of undefined
    at Object.transform (module.js:19)
    at eval (module.js:19)
    at e.render (module.js:19)
    at e.onDataReceived (module.js:19)
    at u.emit (index.js:129)
    at e.emit (emitter.ts:11)
    at e.t.handleQueryResult (sdk.ts:1)
    at Object.next (metrics_panel_ctrl.ts:82)
    at t.__tryOrUnsub (Subscriber.js:194)
    at t.next (Subscriber.js:132)

Screenshot of datatable error:
![Screen Shot 2019-10-04 at 1 57 25 PM](https://user-images.githubusercontent.com/22607854/66229028-edcf6200-e6ae-11e9-8640-3330786208c7.png)

**Comment by societymartingale** [comment]
@satishdotpatel : grafana-datatable-panel now works with Grafana v6.4.2 .

**Comment by satishdotpatel** [comment]
Awesomeness!!! Thank you so much I will upgrade it asap 👍

**Comment by societymartingale** [comment]
@satishdotpatel , I'm guessing this issue can be closed now?

**Comment by satishdotpatel** [comment]
Yes this has been resolved.
