### ISSUE TITLE
Cannot reinitialise DataTable (Grafana 6.4)

### ISSUE THREAD

**Issue by EnergizerBat** [briangann/grafana-datatable-panel#73]
Receive the  following error with datatables and grafana-sensu-app.
"DataTables warning: table id=datatable-panel-table-2 - Cannot reinitialise DataTable. 
For more information about this error, please see http://datatables.net/tn/3"

Also, see error in the following image:
![image](https://user-images.githubusercontent.com/57007110/67578652-e5e46a00-f710-11e9-80c5-0c1a5af4648b.png)

Grafana - 6.4.1
Datatable - 0.0.9
Sensu app - 1.0.6

**Comment by iJack93** [comment]
Hello, try to check the stackoverflow's answer by Oliver Zendel at this link: https://stackoverflow.com/questions/28454203/jquery-datatables-cannot-read-property-adatasort-of-undefined. He solved the problem for me with this tip and maybe could be helpful for you too.

**Comment by mmkamburova** [comment]
Hello,

I'm experiencing a similar problem when I try to add column style rule trough the Grafana UI. The error states:
"DataTables warning: table id=datatable-panel-table-23763571993 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3"

Grafana v7.0.3bash-5.0
Datatable panel: v1.0.2

![image](https://user-images.githubusercontent.com/25443155/86345763-a5a49680-bc64-11ea-901c-175e1ba553e2.png)

Please advise!

Regards,
Maria

**Comment by Saroj-K-Panda** [comment]
Hello,

I am also experiencing similar type of issues, when selecting coloring option as "**Row**" in data-table panel.

Version : **Grafana 7.3.1**
Version : **Data Table Panel 1.0.3**

![image](https://user-images.githubusercontent.com/24875999/101456776-879d3980-395a-11eb-88b7-77a123039ccf.png)

![image](https://user-images.githubusercontent.com/24875999/101457047-f8445600-395a-11eb-9722-9d9966499935.png)

Please advise !

Regards,
Saroj

**Comment by Saroj-K-Panda** [comment]
Hi @briangann,

Could you please suggest on this issue.
Version : Grafana 7.3.1
Version : Data Table Panel 1.0.3

Do I need to install the any other version ? 

Thank you and Regards,
Saroj

**Comment by techtoniq** [comment]
I'm seeing the same error when setting up a new panel trying to configure row threshold colours.
Grafana: v7.3.7
Datatable Panel: v1.0.3
Any suggestions on how to fix or workaround?

**Comment by HamidRezaEbrahimi** [comment]
I'm seeing the same error when setting up a new panel trying to configure row threshold colours.
Grafana: v7.5.2
Datatable Panel: v1.0.3
Any suggestions on how to fix or workaround?

**Comment by briangann** [comment]
let me take a look

**Comment by DanielBridges2** [comment]
Hi @briangann did you have any luck with this issue.

**Comment by snorkman88** [comment]
Is there any other update regarding this issue? I am still facing the same on v9.3.1

**Comment by ugurakyol** [comment]
Is there anything new regarding this issue?
