### ISSUE TITLE
Problems building panel with grunt

### ISSUE THREAD

**Issue by Aga-Schwarz** [briangann/grafana-datatable-panel#77]
Hi there,

first of all, thanks a lot for your contribution.

My setup:
grafana 6.4.5
Windows 10 

Before, I used the 0.0.6 version of the datatable panel, where everything worked as expected. I have made some modifications to the source code and was able to generate the new code into dist folder with grunt.

Now I downloaded the 0.0.9 version via grafana-cli.

My steps:
npm install
grunt 

When I use grunt, I first got the message 
Task "copy:runtime_libs" not found

After removing copy:runtime_libs from grunt.registerTask I get a lot of errors from jshint (screenshot).
Readme says one should execute bower install (I wonder if the errors come from missing this step, or missing copy:runtime_libs), but this does not work with the message "no bower.json present."

Any hint would be greatly appreciated.

<img width="946" alt="grunt_output" src="https://user-images.githubusercontent.com/58482753/70456937-71db0700-1aaf-11ea-9d86-99e9e50d98d1.PNG">

**Comment by briangann** [comment]
The build instructions are outdated, you only need to do this:
```
yarn
yarn build
```
you can also use `yarn dev --watch` for iterative builds.
