### ISSUE TITLE
Buttons Add Column Alias, Add Column Width Hint and Add Rule doesn't work

### ISSUE THREAD

**Issue by biro11** [briangann/grafana-datatable-panel#8]
When I click on buttons **Add Column Alias**, **Add Column Width Hint** or **Add Rule** nothing happens. This issue is after upgrade to 0.0.3 and 0.0.4. Anybody else with this issue? Thanks

**Comment by briangann** [comment]
This functionality isn't 100% implemented for all data sources. I'll work on updating it.

**Comment by s405121** [comment]
Hi @briangann 

Am using ElasticSearch datasource with JSON Data option. Any chance those options work with that combination? I have tried and seeing the same as whats reported above. If not available right now, know if will be available in upcoming release?

Thanks,

Vishnu

**Comment by ismaof** [comment]
Is there any update for Postgres datasource on column alias,  width and add rule?

**Comment by ketan12sharma** [comment]
Any ETA for when it is going to be fixed?

**Comment by briangann** [comment]
working on this now, should have a new release ready over this weekend

**Comment by aguycalledjoe** [comment]
Just started using the plugin and bumped into the same issue. Any eta on when this will be fixed?

**Comment by briangann** [comment]
I'll set aside some more time to fix this, tentatively get it out by monday 1/28

**Comment by busi91** [comment]
Are there any news about it?

**Comment by briangann** [comment]
sorry for the delay, let me work on it this week (also accepting pull requests!)
