### ISSUE TITLE
Issue with sorting on a column

### ISSUE THREAD

**Issue by sartaj10** [briangann/grafana-datatable-panel#80]
Hi, I have a column that refers to the volume of data and it's of type Number and unit as Bytes. When sorting in descending order, it doesn't seem to sort on the actual values and instead the parsed value after applying the units. I've shown that below

<img width="132" alt="Screen Shot 2020-01-27 at 3 21 47 PM" src="https://user-images.githubusercontent.com/5708022/73228414-9439ea00-411a-11ea-89a3-ee28e0871c92.png">

I'm currently using v0.0.9 of the datatable panel.

PS : This might be a duplicate of a previous issue. Any idea when can this be pushed?

**Comment by briangann** [comment]
looking at implementing this now for v1

**Comment by sartaj10** [comment]
@briangann Hi, wondering if there's been any update on this :)
