### ISSUE TITLE
url support

### ISSUE THREAD

**Issue by zot420** [briangann/grafana-datatable-panel#9]
you list the following as a feature

- Rows can have a click-through URL

But I don't see where I can configure the url

**Comment by briangann** [comment]
It's under Options table, in Column Styles. When you set it to "string" you will get the option:

![image](https://user-images.githubusercontent.com/7364245/29954495-eadc4132-8e9d-11e7-8d0f-7ba2e7ac39b3.png)

**Comment by zot42** [comment]
write, but you can't specify what the url is itself. 

I put in a pull [request](https://github.com/briangann/grafana-datatable-panel/pull/10) that does this

**Comment by briangann** [comment]
excellent, let me check it out and merge it!

**Comment by meyerder** [comment]
Custom will do the following quite nice :)

function(data, type, full, meta) {
  return '<a target="_blank" href="https://google.com'+data+'"style="color:green">'+data+'</a>';
}

**Comment by briangann** [comment]
the change has been merged, I'll get this new version published asap. I'm working on a couple of the other issues.

**Comment by adriaand007** [comment]
URL function i not working as expected
to add URL 
http://grafana.example.com:3000/d/odYQvWbmk/server-dashboard?orgId=1&var-servername=${__cell}

This should then open page
http://grafana.example.com:3000/d/odYQvWbmk/server-dashboard?orgId=1&var-servername=server101

What it is giving me is 
http://grafana.example.com:3000server101
or 
http://grafana.example.com:3000/d/odYQvWbmk/server-dashboard?orgId=1&var-servername=${__cell}

Please assist

**Comment by sharadgarg94** [comment]
When can we expect the fix for above issue?

**Comment by briangann** [comment]
it's in v1.0.0, to be published today :)

**Comment by jehutywong** [comment]
v1.0.1 is not working as expect

**Comment by rahuldattania** [comment]
Is there any workaround of the issue in v1.0.1.

**Comment by ganesh-s05** [comment]
@briangann - I am using v.10.1 & i still don't get the clickable URL. The clickable URL still points to the <grafanahost-IP>/(cell_value).. It isn't taking the actual URL. Any workaround/fix available please?

**Comment by briangann** [comment]
there's a new version 1.0.2 which has the real fix for this.

**Comment by ganesh-s05** [comment]
Thanks, @briangann - I upgraded to the latest version of 1.0.2. I am now hitting a different issue with Split cell. Is it mandatory to have the split cell in place? When i give the link & come to the panel view it shows the below error.  Is there a documentation on how to use it?

![image](https://user-images.githubusercontent.com/67759874/86465413-3061c000-bd4f-11ea-84b3-8243832d6d6a.png)

**Comment by AvinKumar** [comment]
@briangann first of all thanks for your plugin, using it from quite some time as an alternate to the table plugin when required. 
Even I upgraded to the latest version v1.0.2 and seeing the same TypeError as mentioned in the above comment by @ganesh-s05. 
If anyone was able to over come this issue then kindly let know what needs to be done.  

-Avin

**Comment by Menaka20** [comment]
Hi..i am using Grafana 7.4.5. Unable to get the correct url to work with the clickable cell in datatable panel. Can somebody please help
