### ISSUE TITLE
Datable is not showing up after installation on Grafana (Panel Plugin not found)

### ISSUE THREAD

**Issue by joseapdmota** [briangann/grafana-datatable-panel#90]
Hello,
In order to use this plugin, i upgraded my Grafana from version 5.4.3 to version 6.0 and lately to version 6.2.
Both in version 6.0 and 6.2 i got the following:
![image](https://user-images.githubusercontent.com/45976969/80814300-8a190300-8bc3-11ea-8e37-abb662a8086f.png)

Even after restarting the docker container.

I used the grafana-cli to install the plugin.

Is this happen before, or did i need some extra configuration?

Thank you.
Jose

**Comment by briangann** [comment]
let me try this - possible side effect of the download link path change

**Comment by briangann** [comment]
the plugin is compatible with versions 6.3 to 6.7.3, the systemjs internal loader was removed recently which was needed for loading the theme.

**Comment by joseapdmota** [comment]
Thanks for the update.
I'll upgrade my Grafana instance then.
