### ISSUE TITLE
Direct link rendered image not displaying the entire table values

### ISSUE THREAD

**Issue by venkatBG** [briangann/grafana-datatable-panel#96]
While trying to share the datatable panel using "Direct link rendered image" option, the entire table is not rendered.
The table contains multiple columns, but when i try to render the image, only the first half of the table gets rendered as image.
The second half of the table which could be viewed after scrolling to right is not captured in the image.

Is there any option to render the image of the entire table with all the columns?

**Comment by briangann** [comment]
will need to investigate this
